import type { ThemeDefinition, ThemeSyntaxOverrides, ThemeSyntaxStyles } from "./types";

function syntax(colors: {
  foreground: string;
  accent: string;
  secondary: string;
  muted: string;
  border: string;
  panel: string;
}, imageRadius = 18): ThemeSyntaxStyles {
  return {
    headingColor: colors.foreground,
    headingBackground: colors.secondary,
    strongColor: colors.accent,
    emphasisColor: colors.foreground,
    deleteColor: colors.border,
    highlightBackground: colors.secondary,
    highlightColor: colors.foreground,
    codeBackground: colors.muted,
    codeColor: colors.foreground,
    quoteBackground: colors.panel,
    listMarkerColor: colors.accent,
    imageBorderColor: colors.border,
    imageRadius,
  };
}

export const themes: ThemeDefinition[] = [
  {
    id: "punk",
    name: "朋克风格",
    description: "高对比、粗边框、荧光撞色，适合强观点内容。",
    colors: {
      background: "#fef15a",
      foreground: "#111111",
      accent: "#ff4fb3",
      secondary: "#00b7ff",
      muted: "#fff6b8",
      border: "#111111",
      panel: "#ffffff",
    },
    fontFamily: 'Arial, "PingFang SC", sans-serif',
    padding: 92,
    baseFontSize: 44,
    lineHeight: 1.45,
    blockGap: 34,
    radius: 0,
    borderWidth: 8,
    syntax: syntax({
      foreground: "#111111",
      accent: "#ff4fb3",
      secondary: "#00b7ff",
      muted: "#fff6b8",
      border: "#111111",
      panel: "#ffffff",
    }, 0),
    motif: "burst",
  },
  {
    id: "pop-art",
    name: "波普艺术",
    description: "明亮色块和圆点图案，适合清单、教程和轻松表达。",
    colors: {
      background: "#ffeb3b",
      foreground: "#101010",
      accent: "#ff1744",
      secondary: "#2979ff",
      muted: "#ffffff",
      border: "#101010",
      panel: "#fffef4",
    },
    fontFamily: 'Impact, Arial, "PingFang SC", sans-serif',
    padding: 86,
    baseFontSize: 42,
    lineHeight: 1.42,
    blockGap: 34,
    radius: 4,
    borderWidth: 7,
    syntax: syntax({
      foreground: "#101010",
      accent: "#ff1744",
      secondary: "#2979ff",
      muted: "#ffffff",
      border: "#101010",
      panel: "#fffef4",
    }, 4),
    motif: "dots",
  },
  {
    id: "memphis",
    name: "孟菲斯",
    description: "几何图形、活泼色彩和拼贴感，适合灵感型笔记。",
    colors: {
      background: "#fff9f0",
      foreground: "#1a1a1a",
      accent: "#ff6b6b",
      secondary: "#4ecdc4",
      muted: "#ffe66d",
      border: "#1a1a1a",
      panel: "#ffffff",
    },
    fontFamily: '"Trebuchet MS", Arial, "PingFang SC", sans-serif',
    padding: 88,
    baseFontSize: 42,
    lineHeight: 1.5,
    blockGap: 32,
    radius: 18,
    borderWidth: 6,
    syntax: syntax({
      foreground: "#1a1a1a",
      accent: "#ff6b6b",
      secondary: "#4ecdc4",
      muted: "#ffe66d",
      border: "#1a1a1a",
      panel: "#ffffff",
    }, 20),
    motif: "memphis",
  },
  {
    id: "iphone-notes",
    name: "iPhone 备忘录",
    description: "白底、黄工具栏和系统排版，像在手机备忘录里写字。",
    colors: {
      background: "#ffffff",
      foreground: "#1d1d1f",
      accent: "#f2b90f",
      secondary: "#f2b90f",
      muted: "#f5f5f7",
      border: "#d1d1d6",
      panel: "#ffffff",
    },
    fontFamily: '-apple-system, BlinkMacSystemFont, "PingFang SC", sans-serif',
    padding: 170,
    baseFontSize: 47,
    lineHeight: 1.58,
    blockGap: 26,
    radius: 30,
    borderWidth: 0,
    syntax: syntax({
      foreground: "#1d1d1f",
      accent: "#f2b90f",
      secondary: "#f2b90f",
      muted: "#f5f5f7",
      border: "#d1d1d6",
      panel: "#ffffff",
    }, 18),
    motif: "notes",
  },
  {
    id: "japanese-minimal",
    name: "日式极简",
    description: "留白、低饱和与克制层级，适合知识卡片和生活方式内容。",
    colors: {
      background: "#f7f1e6",
      foreground: "#27221c",
      accent: "#b63d32",
      secondary: "#ded2bd",
      muted: "#eee3d1",
      border: "#27221c",
      panel: "#fffaf1",
    },
    fontFamily: '"Hiragino Sans", "PingFang SC", serif',
    padding: 104,
    baseFontSize: 40,
    lineHeight: 1.62,
    blockGap: 30,
    radius: 2,
    borderWidth: 2,
    syntax: syntax({
      foreground: "#27221c",
      accent: "#b63d32",
      secondary: "#ded2bd",
      muted: "#eee3d1",
      border: "#27221c",
      panel: "#fffaf1",
    }, 2),
    motif: "none",
  },
  {
    id: "clean-editorial",
    name: "清爽杂志",
    description: "杂志式标题和清晰段落，适合观点、书摘和长文拆图。",
    colors: {
      background: "#f4f7fb",
      foreground: "#172033",
      accent: "#2454ff",
      secondary: "#dbe5ff",
      muted: "#e9eef7",
      border: "#172033",
      panel: "#ffffff",
    },
    fontFamily: 'Georgia, "PingFang SC", serif',
    padding: 88,
    baseFontSize: 41,
    lineHeight: 1.56,
    blockGap: 32,
    radius: 10,
    borderWidth: 2,
    syntax: syntax({
      foreground: "#172033",
      accent: "#2454ff",
      secondary: "#dbe5ff",
      muted: "#e9eef7",
      border: "#172033",
      panel: "#ffffff",
    }, 14),
    motif: "grid",
  },
  {
    id: "soft-magazine",
    name: "柔和画报",
    description: "轻盈色彩和画报式卡片，适合情绪、穿搭和清单内容。",
    colors: {
      background: "#ffe8ef",
      foreground: "#2e2430",
      accent: "#e84a7f",
      secondary: "#8bd3dd",
      muted: "#fff6f8",
      border: "#2e2430",
      panel: "#fffdfb",
    },
    fontFamily: '"Avenir Next", Arial, "PingFang SC", sans-serif',
    padding: 86,
    baseFontSize: 41,
    lineHeight: 1.55,
    blockGap: 32,
    radius: 24,
    borderWidth: 3,
    syntax: syntax({
      foreground: "#2e2430",
      accent: "#e84a7f",
      secondary: "#8bd3dd",
      muted: "#fff6f8",
      border: "#2e2430",
      panel: "#fffdfb",
    }, 24),
    motif: "dots",
  },
  {
    id: "high-contrast-poster",
    name: "高对比海报",
    description: "黑白底色和强烈强调色，适合标题党和重点总结。",
    colors: {
      background: "#111111",
      foreground: "#ffffff",
      accent: "#ffdf00",
      secondary: "#ff4f5e",
      muted: "#2a2a2a",
      border: "#ffffff",
      panel: "#181818",
    },
    fontFamily: 'Arial Black, Arial, "PingFang SC", sans-serif',
    padding: 82,
    baseFontSize: 42,
    lineHeight: 1.45,
    blockGap: 34,
    radius: 0,
    borderWidth: 5,
    syntax: syntax({
      foreground: "#ffffff",
      accent: "#ffdf00",
      secondary: "#ff4f5e",
      muted: "#2a2a2a",
      border: "#ffffff",
      panel: "#181818",
    }, 0),
    motif: "grid",
  },
];

export const defaultTheme = themes[0];

export function getThemeById(id: string): ThemeDefinition {
  return themes.find((theme) => theme.id === id) ?? defaultTheme;
}

export function resolveThemeSyntax(
  theme: ThemeDefinition,
  overrides: ThemeSyntaxOverrides = {},
): ThemeSyntaxStyles {
  return { ...theme.syntax, ...overrides };
}
