import type { ThemeDefinition, ThemeSyntaxOverrides, ThemeSyntaxStyles } from "./types";

function syntax(colors: {
  foreground: string;
  accent: string;
  secondary: string;
  muted: string;
  border: string;
  panel: string;
}, imageRadius = 18): ThemeSyntaxStyles {
  return {
    headingColor: colors.foreground,
    headingBackground: colors.secondary,
    strongColor: colors.accent,
    emphasisColor: colors.foreground,
    deleteColor: colors.border,
    highlightBackground: colors.secondary,
    highlightColor: colors.foreground,
    codeBackground: colors.muted,
    codeColor: colors.foreground,
    quoteBackground: colors.panel,
    listMarkerColor: colors.accent,
    imageBorderColor: colors.border,
    imageRadius,
  };
}

export const themes: ThemeDefinition[] = [
  {
    id: "punk",
    name: "朋克风格",
    description: "高对比、粗边框、荧光撞色，适合强观点内容。",
    colors: {
      background: "#fef15a",
      foreground: "#111111",
      accent: "#ff4fb3",
      secondary: "#00b7ff",
      muted: "#fff6b8",
      border: "#111111",
      panel: "#ffffff",
    },
    fontFamily: 'Arial, "PingFang SC", sans-serif',
    padding: 92,
    baseFontSize: 44,
    lineHeight: 1.45,
    blockGap: 34,
    radius: 0,
    borderWidth: 8,
    syntax: syntax({
      foreground: "#111111",
      accent: "#ff4fb3",
      secondary: "#00b7ff",
      muted: "#fff6b8",
      border: "#111111",
      panel: "#ffffff",
    }, 0),
    motif: "burst",
  },
  {
    id: "pop-art",
    name: "波普艺术",
    description: "明亮色块和圆点图案，适合清单、教程和轻松表达。",
    colors: {
      background: "#ffeb3b",
      foreground: "#101010",
      accent: "#ff1744",
      secondary: "#2979ff",
      muted: "#ffffff",
      border: "#101010",
      panel: "#fffef4",
    },
    fontFamily: 'Impact, Arial, "PingFang SC", sans-serif',
    padding: 86,
    baseFontSize: 42,
    lineHeight: 1.42,
    blockGap: 34,
    radius: 4,
    borderWidth: 7,
    syntax: syntax({
      foreground: "#101010",
      accent: "#ff1744",
      secondary: "#2979ff",
      muted: "#ffffff",
      border: "#101010",
      panel: "#fffef4",
    }, 4),
    motif: "dots",
  },
  {
    id: "memphis",
    name: "孟菲斯",
    description: "几何图形、活泼色彩和拼贴感，适合灵感型笔记。",
    colors: {
      background: "#fff9f0",
      foreground: "#1a1a1a",
      accent: "#ff6b6b",
      secondary: "#4ecdc4",
      muted: "#ffe66d",
      border: "#1a1a1a",
      panel: "#ffffff",
    },
    fontFamily: '"Trebuchet MS", Arial, "PingFang SC", sans-serif',
    padding: 88,
    baseFontSize: 42,
    lineHeight: 1.5,
    blockGap: 32,
    radius: 18,
    borderWidth: 6,
    syntax: syntax({
      foreground: "#1a1a1a",
      accent: "#ff6b6b",
      secondary: "#4ecdc4",
      muted: "#ffe66d",
      border: "#1a1a1a",
      panel: "#ffffff",
    }, 20),
    motif: "memphis",
  },
  {
    id: "iphone-notes",
    name: "iPhone 备忘录",
    description: "白底、黄工具栏和系统排版，像在手机备忘录里写字。",
    colors: {
      background: "#ffffff",
      foreground: "#1d1d1f",
      accent: "#f2b90f",
      secondary: "#f2b90f",
      muted: "#f5f5f7",
      border: "#d1d1d6",
      panel: "#ffffff",
    },
    fontFamily: '-apple-system, BlinkMacSystemFont, "PingFang SC", sans-serif',
    padding: 170,
    baseFontSize: 47,
    lineHeight: 1.58,
    blockGap: 26,
    radius: 30,
    borderWidth: 0,
    syntax: syntax({
      foreground: "#1d1d1f",
      accent: "#f2b90f",
      secondary: "#f2b90f",
      muted: "#f5f5f7",
      border: "#d1d1d6",
      panel: "#ffffff",
    }, 18),
    motif: "notes",
  },
  {
    id: "japanese-minimal",
    name: "日式极简",
    description: "留白、低饱和与克制层级，适合知识卡片和生活方式内容。",
    colors: {
      background: "#f7f1e6",
      foreground: "#27221c",
      accent: "#b63d32",
      secondary: "#ded2bd",
      muted: "#eee3d1",
      border: "#27221c",
      panel: "#fffaf1",
    },
    fontFamily: '"Hiragino Sans", "PingFang SC", serif',
    padding: 104,
    baseFontSize: 40,
    lineHeight: 1.62,
    blockGap: 30,
    radius: 2,
    borderWidth: 2,
    syntax: syntax({
      foreground: "#27221c",
      accent: "#b63d32",
      secondary: "#ded2bd",
      muted: "#eee3d1",
      border: "#27221c",
      panel: "#fffaf1",
    }, 2),
    motif: "none",
  },
  {
    id: "clean-editorial",
    name: "清爽杂志",
    description: "杂志式标题和清晰段落，适合观点、书摘和长文拆图。",
    colors: {
      background: "#f4f7fb",
      foreground: "#172033",
      accent: "#2454ff",
      secondary: "#dbe5ff",
      muted: "#e9eef7",
      border: "#172033",
      panel: "#ffffff",
    },
    fontFamily: 'Georgia, "PingFang SC", serif',
    padding: 88,
    baseFontSize: 41,
    lineHeight: 1.56,
    blockGap: 32,
    radius: 10,
    borderWidth: 2,
    syntax: syntax({
      foreground: "#172033",
      accent: "#2454ff",
      secondary: "#dbe5ff",
      muted: "#e9eef7",
      border: "#172033",
      panel: "#ffffff",
    }, 14),
    motif: "grid",
  },
  {
    id: "soft-magazine",
    name: "柔和画报",
    description: "轻盈色彩和画报式卡片，适合情绪、穿搭和清单内容。",
    colors: {
      background: "#ffe8ef",
      foreground: "#2e2430",
      accent: "#e84a7f",
      secondary: "#8bd3dd",
      muted: "#fff6f8",
      border: "#2e2430",
      panel: "#fffdfb",
    },
    fontFamily: '"Avenir Next", Arial, "PingFang SC", sans-serif',
    padding: 86,
    baseFontSize: 41,
    lineHeight: 1.55,
    blockGap: 32,
    radius: 24,
    borderWidth: 3,
    syntax: syntax({
      foreground: "#2e2430",
      accent: "#e84a7f",
      secondary: "#8bd3dd",
      muted: "#fff6f8",
      border: "#2e2430",
      panel: "#fffdfb",
    }, 24),
    motif: "dots",
  },
  {
    id: "high-contrast-poster",
    name: "高对比海报",
    description: "黑白底色和强烈强调色，适合标题党和重点总结。",
    colors: {
      background: "#111111",
      foreground: "#ffffff",
      accent: "#ffdf00",
      secondary: "#ff4f5e",
      muted: "#2a2a2a",
      border: "#ffffff",
      panel: "#181818",
    },
    fontFamily: 'Arial Black, Arial, "PingFang SC", sans-serif',
    padding: 82,
    baseFontSize: 42,
    lineHeight: 1.45,
    blockGap: 34,
    radius: 0,
    borderWidth: 5,
    syntax: syntax({
      foreground: "#ffffff",
      accent: "#ffdf00",
      secondary: "#ff4f5e",
      muted: "#2a2a2a",
      border: "#ffffff",
      panel: "#181818",
    }, 0),
    motif: "grid",
  },
  {
    id: "minimalist",
    name: "极简主义",
    description: "黑白灰、细分隔和大留白，适合理性笔记与清单。",
    colors: {
      background: "#fbfbfa",
      foreground: "#161616",
      accent: "#4a4a4a",
      secondary: "#e8e8e5",
      muted: "#f2f2ef",
      border: "#c8c8c2",
      panel: "#ffffff",
    },
    fontFamily: 'Helvetica, Arial, "PingFang SC", sans-serif',
    padding: 116,
    baseFontSize: 39,
    lineHeight: 1.6,
    blockGap: 30,
    radius: 6,
    borderWidth: 1,
    syntax: syntax({
      foreground: "#161616",
      accent: "#4a4a4a",
      secondary: "#e8e8e5",
      muted: "#f2f2ef",
      border: "#c8c8c2",
      panel: "#ffffff",
    }, 8),
    motif: "none",
  },
  {
    id: "elegant-vintage",
    name: "优雅复古",
    description: "旧纸质感、深棕红和衬线排版，适合书摘与历史内容。",
    colors: {
      background: "#f2e4c8",
      foreground: "#382617",
      accent: "#8f2f24",
      secondary: "#d8bf93",
      muted: "#ead7b4",
      border: "#5f4328",
      panel: "#fff3d8",
    },
    fontFamily: 'Baskerville, Georgia, "Songti SC", serif',
    padding: 96,
    baseFontSize: 41,
    lineHeight: 1.62,
    blockGap: 31,
    radius: 8,
    borderWidth: 3,
    syntax: syntax({
      foreground: "#382617",
      accent: "#8f2f24",
      secondary: "#d8bf93",
      muted: "#ead7b4",
      border: "#5f4328",
      panel: "#fff3d8",
    }, 12),
    motif: "grid",
  },
  {
    id: "futuristic-tech",
    name: "未来科技",
    description: "深色界面、霓虹蓝紫和数据感网格，适合科技分析。",
    colors: {
      background: "#07101f",
      foreground: "#e8f7ff",
      accent: "#00d9ff",
      secondary: "#6c4dff",
      muted: "#11243a",
      border: "#39f0ff",
      panel: "#0b1728",
    },
    fontFamily: '"Space Mono", Menlo, Consolas, "PingFang SC", monospace',
    padding: 82,
    baseFontSize: 39,
    lineHeight: 1.52,
    blockGap: 30,
    radius: 14,
    borderWidth: 2,
    syntax: syntax({
      foreground: "#e8f7ff",
      accent: "#00d9ff",
      secondary: "#6c4dff",
      muted: "#11243a",
      border: "#39f0ff",
      panel: "#0b1728",
    }, 14),
    motif: "grid",
  },
  {
    id: "scandinavian",
    name: "斯堪的纳维亚",
    description: "明亮白底、浅蓝木色和温和几何，适合生活方式内容。",
    colors: {
      background: "#f8fbfc",
      foreground: "#23313a",
      accent: "#7ca6b8",
      secondary: "#d9c8ad",
      muted: "#eef3f4",
      border: "#b9c9cf",
      panel: "#ffffff",
    },
    fontFamily: 'Futura, "Avenir Next", Arial, "PingFang SC", sans-serif',
    padding: 94,
    baseFontSize: 40,
    lineHeight: 1.58,
    blockGap: 30,
    radius: 16,
    borderWidth: 2,
    syntax: syntax({
      foreground: "#23313a",
      accent: "#7ca6b8",
      secondary: "#d9c8ad",
      muted: "#eef3f4",
      border: "#b9c9cf",
      panel: "#ffffff",
    }, 18),
    motif: "memphis",
  },
  {
    id: "art-deco",
    name: "艺术装饰",
    description: "黑金配色、几何边框和爵士时代气质，适合金句卡片。",
    colors: {
      background: "#0e0b12",
      foreground: "#fff6dc",
      accent: "#d4af37",
      secondary: "#24314f",
      muted: "#1a1520",
      border: "#d4af37",
      panel: "#17111d",
    },
    fontFamily: '"Copperplate", "Bodoni 72", Georgia, "Songti SC", serif',
    padding: 90,
    baseFontSize: 41,
    lineHeight: 1.5,
    blockGap: 32,
    radius: 0,
    borderWidth: 5,
    syntax: syntax({
      foreground: "#fff6dc",
      accent: "#d4af37",
      secondary: "#24314f",
      muted: "#1a1520",
      border: "#d4af37",
      panel: "#17111d",
    }, 0),
    motif: "burst",
  },
  {
    id: "cyberpunk",
    name: "赛博朋克",
    description: "霓虹粉蓝、暗夜都市和故障感层级，适合趋势与观点。",
    colors: {
      background: "#080812",
      foreground: "#f4f7ff",
      accent: "#ff2bd6",
      secondary: "#00e5ff",
      muted: "#1b1230",
      border: "#5cffd6",
      panel: "#100d1f",
    },
    fontFamily: '"Space Mono", Menlo, Consolas, "PingFang SC", monospace',
    padding: 78,
    baseFontSize: 40,
    lineHeight: 1.48,
    blockGap: 32,
    radius: 4,
    borderWidth: 4,
    syntax: syntax({
      foreground: "#f4f7ff",
      accent: "#ff2bd6",
      secondary: "#00e5ff",
      muted: "#1b1230",
      border: "#5cffd6",
      panel: "#100d1f",
    }, 4),
    motif: "grid",
  },
  {
    id: "vaporwave",
    name: "蒸汽波",
    description: "粉紫青蓝、复古互联网和梦幻网格，适合怀旧灵感。",
    colors: {
      background: "#ffe1f5",
      foreground: "#241447",
      accent: "#ff5fc8",
      secondary: "#39d9e8",
      muted: "#f8edff",
      border: "#6b49c8",
      panel: "#fff8ff",
    },
    fontFamily: '"Times New Roman", Georgia, "Songti SC", serif',
    padding: 86,
    baseFontSize: 41,
    lineHeight: 1.54,
    blockGap: 32,
    radius: 18,
    borderWidth: 3,
    syntax: syntax({
      foreground: "#241447",
      accent: "#ff5fc8",
      secondary: "#39d9e8",
      muted: "#f8edff",
      border: "#6b49c8",
      panel: "#fff8ff",
    }, 18),
    motif: "grid",
  },
  {
    id: "bauhaus",
    name: "包豪斯",
    description: "红黄蓝基础几何与理性网格，适合框架、模型和方法论。",
    colors: {
      background: "#f4f0e6",
      foreground: "#111111",
      accent: "#e53935",
      secondary: "#f7c948",
      muted: "#f9f6ee",
      border: "#111111",
      panel: "#ffffff",
    },
    fontFamily: 'Futura, Helvetica, Arial, "PingFang SC", sans-serif',
    padding: 84,
    baseFontSize: 40,
    lineHeight: 1.48,
    blockGap: 30,
    radius: 0,
    borderWidth: 4,
    syntax: syntax({
      foreground: "#111111",
      accent: "#e53935",
      secondary: "#f7c948",
      muted: "#f9f6ee",
      border: "#111111",
      panel: "#ffffff",
    }, 0),
    motif: "memphis",
  },
  {
    id: "constructivism",
    name: "构成主义",
    description: "红黑斜线、结构张力和宣传海报感，适合强论点总结。",
    colors: {
      background: "#f2eadf",
      foreground: "#151515",
      accent: "#d71920",
      secondary: "#2a2a2a",
      muted: "#e3d6c8",
      border: "#151515",
      panel: "#fff7eb",
    },
    fontFamily: 'Arial Black, Impact, "PingFang SC", sans-serif',
    padding: 80,
    baseFontSize: 41,
    lineHeight: 1.42,
    blockGap: 32,
    radius: 0,
    borderWidth: 5,
    syntax: syntax({
      foreground: "#151515",
      accent: "#d71920",
      secondary: "#2a2a2a",
      muted: "#e3d6c8",
      border: "#151515",
      panel: "#fff7eb",
    }, 0),
    motif: "burst",
  },
  {
    id: "victorian",
    name: "维多利亚",
    description: "繁复边框、古典衬线和旧书页色调，适合长文摘录。",
    colors: {
      background: "#ead8b8",
      foreground: "#321f14",
      accent: "#8b1e1e",
      secondary: "#c7a46a",
      muted: "#f1e2c5",
      border: "#5a3821",
      panel: "#fff0cf",
    },
    fontFamily: 'Georgia, "Times New Roman", "Songti SC", serif',
    padding: 94,
    baseFontSize: 40,
    lineHeight: 1.64,
    blockGap: 30,
    radius: 2,
    borderWidth: 6,
    syntax: syntax({
      foreground: "#321f14",
      accent: "#8b1e1e",
      secondary: "#c7a46a",
      muted: "#f1e2c5",
      border: "#5a3821",
      panel: "#fff0cf",
    }, 10),
    motif: "dots",
  },
  {
    id: "neo-baroque",
    name: "新巴洛克",
    description: "深红金色、戏剧明暗和华丽层次，适合奢华感内容。",
    colors: {
      background: "#1b0910",
      foreground: "#fff1cf",
      accent: "#d4af37",
      secondary: "#7d1624",
      muted: "#2a1018",
      border: "#c8982b",
      panel: "#260d16",
    },
    fontFamily: '"Bodoni 72", Didot, Georgia, "Songti SC", serif',
    padding: 88,
    baseFontSize: 41,
    lineHeight: 1.55,
    blockGap: 32,
    radius: 16,
    borderWidth: 4,
    syntax: syntax({
      foreground: "#fff1cf",
      accent: "#d4af37",
      secondary: "#7d1624",
      muted: "#2a1018",
      border: "#c8982b",
      panel: "#260d16",
    }, 18),
    motif: "burst",
  },
  {
    id: "german-expressionism",
    name: "德国表现主义",
    description: "暗色剧场、尖锐对比和木刻感，适合情绪化叙事。",
    colors: {
      background: "#151012",
      foreground: "#f5e6c8",
      accent: "#c51f2b",
      secondary: "#d7a632",
      muted: "#261b1d",
      border: "#f5e6c8",
      panel: "#1f1719",
    },
    fontFamily: '"Arial Narrow", Impact, "PingFang SC", sans-serif',
    padding: 82,
    baseFontSize: 41,
    lineHeight: 1.46,
    blockGap: 34,
    radius: 0,
    borderWidth: 5,
    syntax: syntax({
      foreground: "#f5e6c8",
      accent: "#c51f2b",
      secondary: "#d7a632",
      muted: "#261b1d",
      border: "#f5e6c8",
      panel: "#1f1719",
    }, 0),
    motif: "grid",
  },
];

export const defaultTheme = themes[0];

export function getThemeById(id: string): ThemeDefinition {
  return themes.find((theme) => theme.id === id) ?? defaultTheme;
}

export function resolveThemeSyntax(
  theme: ThemeDefinition,
  overrides: ThemeSyntaxOverrides = {},
): ThemeSyntaxStyles {
  return { ...theme.syntax, ...overrides };
}
