import type { BrandIcon } from "./types";

export const BRAND_ICONS: BrandIcon[] = [
  {
    id: "codex",
    name: "Codex",
    mark: "Cx",
    className: "bg-white text-zinc-950",
    src: "/logo/codex.svg",
  },
  {
    id: "openai",
    name: "OpenAI",
    mark: "OA",
    className: "bg-white text-zinc-950",
    src: "/logo/openai.svg",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    mark: "A",
    className: "bg-white text-zinc-950",
    src: "/logo/anthropic.svg",
  },
  {
    id: "alibaba",
    name: "Alibaba",
    mark: "A",
    className: "bg-white text-zinc-950",
    src: "/logo/alibaba.svg",
  },
  {
    id: "antigravity",
    name: "Antigravity",
    mark: "Ag",
    className: "bg-white text-zinc-950",
    src: "/logo/antigravity.svg",
  },
  {
    id: "apple",
    name: "Apple",
    mark: "Ap",
    className: "bg-white text-zinc-950",
    src: "/logo/apple.svg",
  },
  {
    id: "baidu",
    name: "Baidu",
    mark: "Bd",
    className: "bg-white text-zinc-950",
    src: "/logo/baidu.svg",
  },
  {
    id: "capcut",
    name: "CapCut",
    mark: "Cc",
    className: "bg-white text-zinc-950",
    src: "/logo/capcut.svg",
  },
  {
    id: "claudecode",
    name: "Claude Code",
    mark: "CC",
    className: "bg-white text-zinc-950",
    src: "/logo/claudecode.svg",
  },
  {
    id: "cline",
    name: "Cline",
    mark: "Cl",
    className: "bg-white text-zinc-950",
    src: "/logo/cline.svg",
  },
  {
    id: "cursor",
    name: "Cursor",
    mark: "Cu",
    className: "bg-white text-zinc-950",
    src: "/logo/cursor.svg",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    mark: "Ds",
    className: "bg-white text-zinc-950",
    src: "/logo/deepseek.svg",
  },
  {
    id: "dify",
    name: "Dify",
    mark: "Df",
    className: "bg-white text-zinc-950",
    src: "/logo/dify.svg",
  },
  {
    id: "figma",
    name: "Figma",
    mark: "Fg",
    className: "bg-white text-zinc-950",
    src: "/logo/figma.svg",
  },
  {
    id: "github",
    name: "GitHub",
    mark: "Gh",
    className: "bg-white text-zinc-950",
    src: "/logo/github.svg",
  },
  {
    id: "google",
    name: "Google",
    mark: "Go",
    className: "bg-white text-zinc-950",
    src: "/logo/google.svg",
  },
  {
    id: "grok",
    name: "Grok",
    mark: "Gk",
    className: "bg-white text-zinc-950",
    src: "/logo/grok.svg",
  },
  {
    id: "huawei",
    name: "Huawei",
    mark: "Hw",
    className: "bg-white text-zinc-950",
    src: "/logo/huawei.svg",
  },
  {
    id: "jimeng",
    name: "Jimeng",
    mark: "Jm",
    className: "bg-white text-zinc-950",
    src: "/logo/jimeng.svg",
  },
  {
    id: "kiro",
    name: "Kiro",
    mark: "Ki",
    className: "bg-white text-zinc-950",
    src: "/logo/kiro.svg",
  },
  {
    id: "moonshot",
    name: "Moonshot",
    mark: "Ms",
    className: "bg-white text-zinc-950",
    src: "/logo/moonshot.svg",
  },
  {
    id: "nanobanana",
    name: "Nano Banana",
    mark: "NB",
    className: "bg-white text-zinc-950",
    src: "/logo/nanobanana.svg",
  },
  {
    id: "notion",
    name: "Notion",
    mark: "No",
    className: "bg-white text-zinc-950",
    src: "/logo/notion.svg",
  },
  {
    id: "qoder",
    name: "Qoder",
    mark: "Qd",
    className: "bg-white text-zinc-950",
    src: "/logo/qoder.svg",
  },
];
